from pathlib import Path

class Pixmap:
    def save(self, output: str | Path, *args: str, **kwargs: str) -> None: ...

class Page:
    def get_pixmap(self, dpi: int = 200, *args: str, **kwargs: str) -> Pixmap: ...

class Document:
    def __len__(self) -> int: ...
    def load_page(self, page_num: int) -> Page: ...
    def close(self) -> None: ...
    def __enter__(self) -> Document: ...
    def __exit__(self, *args: object) -> None: ...

def open(filename: str | Path) -> Document: ...
